# Generated by Django 3.1 on 2020-09-01 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The Title of the Article', max_length=200, unique=True, verbose_name='Article Title')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The last time the model has been updated/changed.', verbose_name='Last Updated')),
                ('posted_on', models.DateTimeField(auto_now=True, help_text='The date when the article was posted.', verbose_name='Date Posted')),
                ('content', markdownx.models.MarkdownxField()),
                ('main_category', models.CharField(help_text='The main category of the Article.', max_length=200, verbose_name='Main Article Category')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('categories', models.CharField(help_text='A seralized list of categories that the article belongs to.', max_length=255, verbose_name='MetaData Article Categories')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
