# Generated by Django 3.1 on 2020-09-04 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_resources', '0004_auto_20200902_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resources_index_card',
            options={'verbose_name_plural': 'Resources Index Cards'},
        ),
        migrations.AlterField(
            model_name='article',
            name='main_category',
            field=models.ForeignKey(help_text='The associated Article Index Card model instance.', on_delete=django.db.models.deletion.CASCADE, to='education_resources.resources_index_card', verbose_name='Associated Article Index Card'),
        ),
        migrations.AlterField(
            model_name='resources_index_card',
            name='card_category',
            field=models.CharField(choices=[('Finance', 'finance'), ('Software Development', 'software_development')], help_text='The category of resources that the card relates to. It is used by the templating engine to sort the card.', max_length=50, verbose_name='Card Application Category'),
        ),
    ]
