# Generated by Django 3.1 on 2020-09-04 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_resources', '0006_auto_20200904_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_category',
            field=models.ForeignKey(help_text='The associated Article Index Card model instance.', on_delete=django.db.models.deletion.CASCADE, to='education_resources.resources_index_card', verbose_name='Associated Article Index Card'),
        ),
    ]
