# Generated by Django 3.1.1 on 2020-09-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_resources', '0010_catalogueelement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogueelement',
            options={'verbose_name_plural': 'Catalogue Elements'},
        ),
        migrations.AddField(
            model_name='catalogueelement',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
