# Generated by Django 3.1 on 2020-08-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications_Index_Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_icons', models.CharField(help_text="A ':' Serialized list of icon image names to be used in the card header.", max_length=225, verbose_name='Card Icons')),
                ('card_image', models.CharField(help_text='The name of the image file to be included in the Card.', max_length=100, verbose_name='Card Image')),
                ('card_title', models.CharField(help_text='The Title Text for the Card.', max_length=100, verbose_name='Card Title')),
                ('card_description', models.TextField(help_text='The Long Description of the Card.', verbose_name='Card Description')),
                ('button_a_txt', models.CharField(help_text='The main text content of the first button.', max_length=50, verbose_name='Button A Text')),
                ('button_a_icon', models.CharField(help_text='The name of the icon image to be inserted into the first button.', max_length=50, verbose_name='Button A Icon')),
                ('button_a_href', models.CharField(help_text='The url that the first button is supposed to lead to.', max_length=225, verbose_name='Button A Href')),
                ('button_b_text', models.CharField(help_text='The main text content of the second button.', max_length=50, verbose_name='Button B Text')),
                ('button_b_icon', models.CharField(help_text='The name of the icon image to be inserted into the second button.', max_length=50, verbose_name='Button B Icon')),
                ('button_b_href', models.CharField(help_text='The url that the second button is supposed to lead to.', max_length=225, verbose_name='Button B Href')),
                ('card_category', models.CharField(help_text='The category of project that the card relates to. It is used by the templating engine to sort the card.', max_length=50, verbose_name='Card Application Category')),
            ],
        ),
    ]
