# Generated by Django 3.1 on 2020-08-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications_index_cards',
            old_name='button_a_txt',
            new_name='button_a_text',
        ),
    ]
