# Generated by Django 3.1 on 2020-09-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_core', '0002_auto_20200827_0633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications_index_cards',
            options={'verbose_name_plural': 'Application Index Cards'},
        ),
        migrations.AddField(
            model_name='applications_index_cards',
            name='card_sub_category',
            field=models.CharField(help_text='The sub-category of an application that is used to sort application cards within a single category.', max_length=55, null=True, verbose_name='Card Sub-Category'),
        ),
        migrations.AlterField(
            model_name='applications_index_cards',
            name='card_category',
            field=models.CharField(choices=[('web_applications', 'web_applications'), ('finance_applications', 'finance_applications'), ('abm_applications', 'abm_applications')], help_text='The category of project that the card relates to. It is used by the templating engine to sort the card.', max_length=50, verbose_name='Card Application Category'),
        ),
    ]
