# Generated by Django 3.1.1 on 2020-09-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_core', '0003_auto_20200905_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications_index_cards',
            name='card_category',
            field=models.CharField(choices=[('web_applications', 'web_applications'), ('finance_applications', 'finance_applications'), ('abm_applications', 'abm_applications'), ('dhi_hd_modeling_applications', 'dhi_hd_modeling_applications')], help_text='The category of project that the card relates to. It is used by the templating engine to sort the card.', max_length=50, verbose_name='Card Application Category'),
        ),
        migrations.AlterField(
            model_name='applications_index_cards',
            name='card_sub_category',
            field=models.CharField(default=None, help_text='The sub-category of an application that is used to sort application cards within a single category.', max_length=55, null=True, verbose_name='Card Sub-Category'),
        ),
    ]
